Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,17 +48,24 @@ jobs:
 
     - name: Delete Docker dangling image
       run: |
-        echo "$LIGHTSAIL_SSH_KEY" > myperm.pem
-        chmod 600 myperm.pem
-    
-        # Check if there are dangling images before attempting to remove them
-        DANGLING_IMAGES=$(ssh -i myperm.pem $LIGHTSAIL_USERNAME@$LIGHTSAIL_PUBLIC_IP 'docker images -f "dangling=true" -q')
-        
-        if [ -n "$DANGLING_IMAGES" ]; then
-          ssh -i myperm.pem $LIGHTSAIL_USERNAME@$LIGHTSAIL_PUBLIC_IP "docker rmi $DANGLING_IMAGES"
-        else
-          echo "No dangling images to remove."
-        fi
+        try {
+          touch myperm.pem
+          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > myperm.pem
+          chmod 600 myperm.pem
+          #ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'docker rmi $(sudo docker images -f "dangling=true" -q)'
+          ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'docker images -f "dangling=true" -q | xargs docker rmi'
+        } catch (error) {
+          echo "Error while deleting dangling images: $error"
+          exit 1
+        }
+      env:
+        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
+        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
+        LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
+        APP_MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
+        APP_PORT: ${{ secrets.APP_PORT }}
+        APP_RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
+        APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
 
 
     - name: Build and Deploy Docker container on Lightsail
